<?php
/**
 * Do not edit this file. Edit the config files found in {{ path('config-dir', 'wpconfig-dir') }}/ instead.
 * vendorDir {{vendorDir}}
 */

require_once(__DIR__ . '/{{ path('vendor-dir', 'wpconfig-dir') }}/autoload.php');

// REMOTE_ADDR
if(isset($_SERVER['HTTP_CF_CONNECTING_IP'])) {
	$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];
} elseif(isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
	$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];
}

// HTTPS
if(isset($_SERVER['HTTP_CF_VISITOR'])) {
	$data = json_decode($_SERVER['HTTP_CF_VISITOR'], true);
	if(is_array($data) && isset($data['scheme']) && $data['scheme'] == 'https') {
		$_SERVER['HTTPS'] = 'on';
	}
} elseif(isset($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
	if($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
		$_SERVER['HTTPS'] = 'on';
	}
}

require_once(__DIR__ . '/{{ path('config-dir', 'wpconfig-dir') }}/application.php');

if(!defined('WP_HOME')) {
	$scheme = 'http';
	if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
		$scheme = 'https';
	}

	$domain = $_SERVER['HTTP_HOST'];

{% if path('home-dir', 'webroot') == './' %}
	define('WP_HOME', $scheme . '://' . $domain);
{% else %}
	define('WP_HOME', $scheme . '://' . $domain . '/{{ path('home-dir', 'webroot') }}');
{% endif %}
}

if(!defined('WP_SITEURL')) {
{% if path('install-dir', 'home-dir') == './' %}
	define('WP_SITEURL', WP_HOME);
{% else %}
	define('WP_SITEURL', WP_HOME . '/{{ path('install-dir', 'home-dir') }}');
{% endif %}
}

if(!defined('WP_CONTENT_DIR')) {
	define('WP_CONTENT_DIR', WEBROOT . '/{{ path('content-dir', 'home-dir') }}');
}

if(!defined('WP_CONTENT_URL')) {
	define('WP_CONTENT_URL', WP_HOME . '/{{ path('content-dir', 'home-dir') }}');
}

if(!defined('ABSPATH')) {
	define('ABSPATH', WEBROOT . '/{{ path('install-dir', 'webroot') }}');
}

require_once(ABSPATH . 'wp-settings.php');
